Resilience v1.0
Sage-Bionetworks/ResearchKit pull request #87
Opened 2017-06-08 16:51 UTC by dephillipsmichael

This PR is mostly exposing ORK classes publicly and some more functionality with already exposed classes.  

I wrote some magical classes in Resilience that allow completely custom UI for ORKFormStepViewController and ORKQuestionStepViewController while still using 100% of their functionality.  I accomplished this by hooking up corresponding cell and UI element events and feeding those into the existing ORKFSVC or ORQSVC methods.

2017-06-08 16:52 UTC, dephillipsmichael commented on ResearchKit/Common/ORKFormStepViewController.m
> +- (BOOL)isFormItemValidFor:(NSString*)formItemIdentifier {
This is the only added functionality.  I created it specifically so I could check if a field's error message was no longer applicable.

2017-06-08 21:55 UTC, syoung-smallwisdom requested changes
Couple of nits. 

Could you please verify that running the units tests in `ORKTest` also pass. (Travis isn't currently set up to run those.)

Also, please check with Josh that this doesn't code stomp him. Thanks!

2017-06-08 21:55 UTC, syoung-smallwisdom commented on ResearchKit/Common/ORKQuestionStepViewController.h
> +- (void)setAnswer:(id<NSCopying,NSObject,NSCoding>)answer;
Nit: could you please fix the spacing.

2017-06-08 21:55 UTC, syoung-smallwisdom commented on ResearchKit/Common/ORKSurveyAnswerCellForText.h
> + * Allow exxternal classes to set textview's text for answer cell
typo exxternal = external

2017-06-08 21:55 UTC, syoung-smallwisdom commented on ResearchKit/Common/ORKSurveyAnswerCellForText.m
> +- (void) setText:(NSString*)text {
Please change the spacing. Thanks.

2017-06-10 20:28 UTC, dephillipsmichael commented
Tests succeeded

2017-06-12 20:16 UTC, merged